apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data-claim
      - name: grafana-config
        persistentVolumeClaim:
          claimName: grafana-config-claim
      - name: grafana-main-config
        configMap:
          name: grafana-main-config
      containers:
      - env:
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: "1024"
          - name: PGID
            value: "100"
          - name: PGID
            value: "100"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: grafana
                key: db-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana
                key: db-password
          - name: LDAP_BIND_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana
                key: ldap-password
        image: grafana/grafana:11.0.0
        name: grafana
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        - mountPath: /etc/grafana/
          name: grafana-config
        - mountPath: /etc/grafana/grafana.ini
          name: grafana-main-config
          subPath: grafana.ini
        - mountPath: /etc/grafana/ldap.toml
          name: grafana-main-config
          subPath: ldap.toml
      restartPolicy: Always
