apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app.kubernetes.io/name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      volumes:
      - name: jellyseerr-config
        persistentVolumeClaim:
          claimName: jellyseerr-config-claim
      containers:
      - env:
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: "1024"
          - name: PGID
            value: "100"
          - name: LOG_LEVEL
            value: "DEBUG"
        image: fallenbagel/jellyseerr
        name: jellfyin
        ports:
        - containerPort: 5055
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /app/config
            name: jellyseerr-config
