apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: jellyfin-cache
        persistentVolumeClaim:
          claimName: jellyfin-cache-claim
      - name: jellyfin-data
        persistentVolumeClaim:
          claimName: nfs-claim
      - name: video-hardware-device
        hostPath:
          path: /dev/dri/renderD128
      securityContext:
        supplementalGroups:
          - 303
      nodeSelector:
        video-hardware: "true"
      containers:
      - env:
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: "1024"
          - name: PGID
            value: "100"
        image: linuxserver/jellyfin:10.11.0
        name: jellfyin
        ports:
        - containerPort: 8096
          name: http-tcp
          protocol: TCP
        - containerPort: 8920
          name: https-tcp
          protocol: TCP
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 7359
          name: discovery-udp
          protocol: UDP
        volumeMounts:
        - mountPath: /config
          name: jellyfin-config
        - mountPath: /cache
          name: jellyfin-cache
        - mountPath: /data
          name: jellyfin-data
        - mountPath: /dev/dri/renderD128
          name: video-hardware-device
        securityContext:
          privileged: true
      restartPolicy: Always
