apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      volumes:
      - name: mealie-data
        persistentVolumeClaim:
          claimName: mealie-data-claim
      containers:
      - env:
          - name: ALLOW_SIGNUP
            value: "false"
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: "1024"
          - name: PGID
            value: "100"
          - name: BASE_URL
            value: "https://cooking.lab.janissary.xyz"
          - name: DB_ENGINE
            value: "postgres"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: mealie
                key: db-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mealie
                key: db-password
          - name: POSTGRES_SERVER
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "mealie"
          - name: OIDC_ENABLED
            value: "true"
          - name: ALLOW_PASSWORD_LOGIN
            value: "false"
          - name: OIDC_SIGNUP_ENABLED
            value: "true"
          - name: OIDC_CONFIGURATION_URL
            value: "https://auth.janissary.xyz/.well-known/openid-configuration"
          - name: OIDC_CLIENT_ID
            value: "mealie"
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: mealie
                key: oidc-secret
          - name: OIDC_AUTO_REDIRECT
            value: "true"
          - name: OIDC_ADMIN_GROUP
            value: "mealie_admins"
          - name: OIDC_USER_GROUP
            value: "mealie_users"
        image: ghcr.io/mealie-recipes/mealie:v3.3.0
        name: mealie
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/data
          name: mealie-data
      restartPolicy: Always
