apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-claim
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: nfs-claim
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:latest
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: VPN_TYPE
              value: "wireguard"
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-wireguard-private-key
                  key: key
            - name: WIREGUARD_ADDRESSES
              value: "10.67.43.154/32"
            # - name: FIREWALL_VPN_INPUT_PORTS
            #   value: "51820"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          # TODO maybe add firewalled port
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: PUID
              value: "1024"
            - name: PGID
              value: "100"
          volumeMounts:
          - mountPath: /config
            name: qbittorrent-config
          - mountPath: /downloads
            name: qbittorrent-data
