apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-claim
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: nfs-claim
      initContainers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40.0
          restartPolicy: Always
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: VPN_TYPE
              value: "wireguard"
            - name: VPN_SERVICE_PROVIDER
              value: "airvpn"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun
                  key: key
            - name: WIREGUARD_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun
                  key: preshared
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: gluetun
                  key: addr
            - name: FIREWALL_VPN_INPUT_PORTS
              valueFrom:
                secretKeyRef:
                  name: gluetun
                  key: port
            - name: FIREWALL_DEBUG
              value: "true"
            - name: DNS_ADDRESS
              value: "10.128.0.1"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.0.4
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: PUID
              value: "1024"
            - name: PGID
              value: "100"
          volumeMounts:
          - mountPath: /config
            name: qbittorrent-config
          - mountPath: /data
            name: qbittorrent-data
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
