apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      volumes:
        - name: readarr-config
          persistentVolumeClaim:
            claimName: readarr-config-claim
        - name: readarr-data
          persistentVolumeClaim:
            claimName: nfs-claim
      containers:
        - name: readarr
          image: hotio/readarr:latest
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: PUID
              value: "1024"
            - name: PGID
              value: "100"
          ports:
            - containerPort: 8787
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: readarr-config
            - mountPath: /data
              name: readarr-data
