apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      volumes:
      - name: uptime-kuma-data
        persistentVolumeClaim:
          claimName: uptime-kuma-data-claim
      containers:
      - env:
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: "1024"
          - name: PGID
            value: "100"
        image: louislam/uptime-kuma:1
        name: uptime-kuma
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/data
          name: uptime-kuma-data
      restartPolicy: Always
