resource "proxmox_vm_qemu" "anubis" {
  name         = "anubis"
  vmid         = 103
  target_nodes = ["amun"]
  description  = " generated by NixOS"

  bios    = "seabios"
  qemu_os = "l26"
  scsihw  = "virtio-scsi-pci"
  agent   = 1
  kvm     = true
  hotplug = "network,disk,usb"
  tablet  = true
  memory  = 16384

  start_at_node_boot = true
  power_state = "running"

  cpu {
    cores   = 4
    sockets = 1
    type    = "host"
  }

  disks {
    virtio {
      virtio0 {
        disk {
          size    = "96G"
          storage = "local-lvm"
          format  = "raw"
          backup  = true
        }
      }
    }
  }

  network {
    id      = 0
    bridge  = "vmbr0"
    model   = "virtio"
    macaddr = "bc:24:11:16:50:8c"
    firewall = true
  }

  serial {
    id   = 0
    type = "socket"
  }
}

resource "proxmox_vm_qemu" "osiris" {
  name         = "osiris"
  vmid         = 104
  target_nodes = ["amun"]
  description  = " generated by NixOS"

  bios    = "seabios"
  qemu_os = "l26"
  scsihw  = "virtio-scsi-pci"
  agent   = 1
  kvm     = true
  hotplug = "network,disk,usb"
  tablet  = true
  memory  = 8192

  start_at_node_boot = true
  power_state        = "running"

  cpu {
    cores   = 4
    sockets = 1
    type    = "host"
  }

  disks {
    virtio {
      virtio0 {
        disk {
          size    = "96G"
          storage = "local-lvm"
          format  = "raw"
          backup  = true
        }
      }
    }
  }

  network {
    id       = 0
    bridge   = "vmbr0"
    model    = "virtio"
    macaddr  = "bc:24:11:d8:73:2e"
    firewall = true
  }

  serial {
    id   = 0
    type = "socket"
  }
}

resource "proxmox_vm_qemu" "thoth" {
  name         = "thoth"
  vmid         = 101
  target_nodes = ["amun"]
  description  = " generated by NixOS"

  bios    = "seabios"
  qemu_os = "l26"
  scsihw  = "virtio-scsi-pci"
  agent   = 1
  kvm     = true
  hotplug = "network,disk,usb"
  tablet  = true
  memory  = 8192

  start_at_node_boot = true
  power_state        = "running"

  cpu {
    cores   = 4
    sockets = 1
    type    = "host"
  }

  disks {
    virtio {
      virtio0 {
        disk {
          size    = "238888M"
          storage = "local-lvm"
          format  = "raw"
          backup  = true
        }
      }
    }
  }

  network {
    id       = 0
    bridge   = "vmbr0"
    model    = "virtio"
    macaddr  = "bc:24:11:d8:73:2f"
    firewall = true
  }

  serial {
    id   = 0
    type = "socket"
  }
}
