apiVersion: v1
kind: Service
metadata:
  name: calibre-service
spec:
  selector:
    app: calibre
  type: NodePort
  ports:
  - name: calibre-http
    protocol: TCP
    port: 80
    targetPort: http-tcp
