apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app: flaresolverr
  type: NodePort
  ports:
  - name: flaresolverr-http
    protocol: TCP
    port: 80
    targetPort: http
