apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  selector:
    app: home-assistant
  type: NodePort
  ports:
  - name: home-assistant-http
    protocol: TCP
    port: 80
    targetPort: http
