apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
spec:
  selector:
    app: jellyseerr
  type: NodePort
  ports:
  - name: jellyseerr-http
    protocol: TCP
    port: 80
    targetPort: http
