apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  selector:
    app: jellyfin
  type: NodePort
  ports:
  - name: jellyfin-http
    protocol: TCP
    port: 80
    targetPort: http-tcp
  - name: jellyfin-https
    protocol: TCP
    port: 443
    targetPort: https-tcp
