apiVersion: v1
kind: Service
metadata:
  name: lldap
spec:
  selector:
    app: lldap
  type: NodePort
  ports:
  - name: lldap-http
    protocol: TCP
    port: 80
    targetPort: http
  - name: lldap-ldap
    protocol: TCP
    port: 3890
    targetPort: ldap
