apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  type: NodePort
  ports:
  - name: postgres-exporter-http
    protocol: TCP
    port: 9187
    targetPort: http
