apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
spec:
  selector:
    app: qbittorrent
  type: NodePort
  ports:
  - name: qbittorrent-http
    protocol: TCP
    port: 80
    targetPort: http
