apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  labels:
    app.kubernetes.io/name: stirling-pdf
spec:
  selector:
    app: stirling-pdf
  type: NodePort
  ports:
  - name: stirling-pdf-http
    protocol: TCP
    port: 80
    targetPort: http-tcp
