apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
spec:
  selector:
    app: uptime-kuma
  type: NodePort
  ports:
  - name: uptime-kuma-http
    protocol: TCP
    port: 80
    targetPort: http
