apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
