apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-config
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /volume1/Media/Lab/jellyseerr/
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-claim
spec:
  storageClassName: nfs
  volumeName: jellyseerr-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
