apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-claim
spec:
  storageClassName: nfs
  volumeName: jellyfin-cache
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-claim
spec:
  storageClassName: nfs
  volumeName: jellyfin-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
