apiVersion: v1
kind: PersistentVolume
metadata:
  name: lldap-data
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: /volume1/Media/Lab/lldap/
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data-claim
spec:
  storageClassName: nfs
  volumeName: lldap-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
