apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-data
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /volume1/Media/Lab/mealie/data
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-claim
spec:
  storageClassName: nfs
  volumeName: mealie-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
