apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
spec:
  storageClassName: nfs
  volumeName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
