apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Ti
  nfs:
    path: /volume1/Media
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
spec:
  storageClassName: nfs
  volumeName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
