apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /volume1/Media/Lab/prometheus/data
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-config
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: /volume1/Media/Lab/prometheus/config
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-claim
spec:
  storageClassName: nfs
  volumeName: prometheus-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-config-claim
spec:
  storageClassName: nfs
  volumeName: prometheus-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
