apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: /volume1/Media/Lab/radarr/
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-claim
spec:
  storageClassName: nfs
  volumeName: radarr-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
