apiVersion: v1
kind: PersistentVolume
metadata:
  name: suwayomi-manga
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Ti
  nfs:
    path: /volume1/Media/Manga
    server: hesiod.lab.janissary.xyz
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-manga-claim
spec:
  storageClassName: nfs
  volumeName: suwayomi-manga
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
