apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: calibre-ingress
  annotations:
    gethomepage.dev/href: "https://library.lab.janissary.xyz"
    gethomepage.dev/icon: "calibre-web.png"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: eBook Library
    gethomepage.dev/group: Media
    gethomepage.dev/name: Calibre
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/widget.type: "calibreweb"
    gethomepage.dev/widget.url: "https://library.lab.janissary.xyz"
    # gethomepage.dev/widget.username: "" TODO figure out how to grab this value from secret
    # gethomepage.dev/widget.password: ""
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`library.lab.janissary.xyz`)
    kind: Rule
    services:
    - name: calibre-service
      port: calibre-http
  tls:
    certResolver: myresolver
