apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`home.lab.janissary.xyz`)
    kind: Rule
    services:
    - name: homepage
      port: http
  tls:
    certResolver: myresolver
    domains:
      - main: "lab.janissary.xyz"
        sans:
          - "*.lab.janissary.xyz"
