apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lldap-ingress
  annotations:
    gethomepage.dev/href: "https://ldap.lab.janissary.xyz"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: LDAP Server
    gethomepage.dev/group: Infra
    gethomepage.dev/name: LLDAP
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`ldap.lab.janissary.xyz`)
    kind: Rule
    services:
    - name: lldap
      port: lldap-http
  tls:
    certResolver: myresolver
