apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  annotations:
    gethomepage.dev/href: "https://prowlarr.lab.janissary.xyz"
    gethomepage.dev/icon: "prowlarr.png"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Indexing for movie/TV/audio downloads
    gethomepage.dev/group: Downloads
    gethomepage.dev/name: prowlarr
    gethomepage.dev/pod-selector: ""
    # gethomepage.dev/widget.type: "prowlarr"
    # gethomepage.dev/widget.url: "https://prowlarr.lab.janissary.xyz"
    # gethomepage.dev/widget.key: "" TODO figure out how to grab this value from secret
    # gethomepage.dev/widget.enableQueue: true
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`prowlarr.lab.janissary.xyz`)
    kind: Rule
    services:
    - name: prowlarr
      port: prowlarr-http
  tls:
    certResolver: myresolver
    domains:
      - main: "lab.janissary.xyz"
        sans:
          - "*.lab.janissary.xyz"
