apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  annotations:
    gethomepage.dev/href: "https://sonarr.lab.janissary.xyz"
    gethomepage.dev/icon: "sonarr.png"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Automated TV show tracking
    gethomepage.dev/group: Infra
    gethomepage.dev/name: sonarr
    gethomepage.dev/pod-selector: ""
    # gethomepage.dev/widget.type: "sonarr"
    # gethomepage.dev/widget.url: "https://sonarr.lab.janissary.xyz"
    # gethomepage.dev/widget.key: "" TODO figure out how to grab this value from secret
    # gethomepage.dev/widget.enableQueue: true
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`sonarr.lab.janissary.xyz`)
    kind: Rule
    services:
    - name: sonarr
      port: sonarr-http
  tls:
    certResolver: myresolver
