alloy:
  mounts:
    varlog: true
  configMap:
    content: |
      discovery.kubernetes "pods" {
        role = "pod"
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint {
          url = "http://loki-gateway/loki/api/v1/push"
        }
      }

      loki.relabel "journal" {
        forward_to = []

        rule {
          source_labels = ["__journal__systemd_unit"]
          target_label  = "systemd_unit"
        }
        rule {
          source_labels = ["__journal__hostname"]
          target_label = "systemd_hostname"
        }
        rule {
          source_labels = ["__journal__transport"]
          target_label = "systemd_transport"
        }
      }

      loki.source.journal "read" {
        forward_to = [loki.write.default.receiver]
        relabel_rules = loki.relabel.journal.rules
        max_age = "12h"
        path = "/var/log/journal"
        labels = {component = "loki.source.journal"}
      }
