apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
data:
  configuration.yaml: |
    # Configure a default setup of Home Assistant (frontend, api, etc)
    default_config:

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    homeassistant:
      auth_providers:
        - type: command_line
          command: /config/ldap-auth.sh
          args: ["http://lldap", "home_assistant", "home_assistant_admin", "home_assistant_local"]
          meta: true

    # Nginx Proxy stuff
    http:
      server_port: 8123
      use_x_forwarded_for: true
      # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
      # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
      #
      # We're running in k8s, so this will just be a cluster IP - we can't
      # really filter for the real proxy IP
      trusted_proxies:
        - 0.0.0.0/0
      # this is publicly exposed, so gotta have some sort of IP banning in place
      ip_ban_enabled: true
      login_attempts_threshold: 10
